@CarRentalPlatform_HostAddress = http://localhost:5012

GET {{CarRentalPlatform_HostAddress}}/api/Rentals/all
Accept: application/json

###

GET {{CarRentalPlatform_HostAddress}}/api/Rentals/allByPage?pageNumber=1&pageSize=3
Accept: application/json


GET {{CarRentalPlatform_HostAddress}}/api/Rentals/6
Accept: application/json

###

POST {{CarRentalPlatform_HostAddress}}/api/Rentals
Content-Type: application/json
Accept-Language: en-US,en;q=0.5


{
  "carId": 2,
  "userId": 1,
  "startDate": "2024-07-08T03:12:54.401Z",
  "endDate": "2024-07-09T03:12:54.401Z",
  "fee": 60
}

###

PUT  {{CarRentalPlatform_HostAddress}}/api/Rentals/9
Content-Type: application/json
Accept-Language: en-US,en;q=0.5


{
    "Id": 9,
    "CarId": 3,
    "UserId": 6,
    "StartDate": "2024-06-25T12:00:00",
    "EndDate": "2024-06-27T12:00:00",
    "Fee": 120,
    "CarMake": "toyota",
    "CarModel": "99",
    "UserName": "guest",
    "Status": 1
}

###

DELETE   {{CarRentalPlatform_HostAddress}}/api/Rentals/4

### 
PUT   {{CarRentalPlatform_HostAddress}}/api/Rentals/status/6
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMTIzNDU2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiMTIzNDU2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MTk0NTA0NTQsImlzcyI6IjIyMklzc3VlciIsImF1ZCI6IjExMVlvdXJBdWRpZW5jZSJ9.9mlD1eBLfUYztDzqsgXJ24ACwYb2qvzkvBFNo04IafM


{
  "status":1
}

