@CarRentalPlatform_HostAddress = http://localhost:5012

GET {{CarRentalPlatform_HostAddress}}/api/Users/all
Accept: application/json

###

GET {{CarRentalPlatform_HostAddress}}/api/cars/allByPage?pageNumber=1&pageSize=3
Accept: application/json

###

GET {{CarRentalPlatform_HostAddress}}/api/Users/1
Accept: application/json

###

POST {{CarRentalPlatform_HostAddress}}/api/Users
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

  {
    "username": "Referer",
    "password": "3333",
    "isAdmin": false,
    "email": "134@ewr.com"
  }

###

PUT  {{CarRentalPlatform_HostAddress}}/api/Users/8
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

  {
    "id": 8,
    "username": "000",
    "password": "99900",
    "isAdmin": false,
    "email": "xxx@234.com"
  }

###

DELETE   {{CarRentalPlatform_HostAddress}}/api/Users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicXFxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoid3d3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTcxODg4NzA5NCwiaXNzIjoiMjIySXNzdWVyIiwiYXVkIjoiMTExWW91ckF1ZGllbmNlIn0.DszRinqlhoKRfCXXdMb2L9bkg-LO8PfSjTaEBl4lgRc


